// data.ts

export interface Animal {
  name: string;
  appearance: string;
}

export const animals: Animal[] = [
  { name: "dog", appearance: "dog 🐶" },
  { name: "cat", appearance: "cat 🐱" },
  { name: "horse", appearance: "horse 🐴" },
  { name: "cow", appearance: "cow 🐮" },
  { name: "pig", appearance: "pig 🐷" },
  { name: "sheep", appearance: "sheep 🐑" },
  { name: "chicken", appearance: "chicken 🐔" },
  { name: "rooster", appearance: "rooster 🐓" },
  { name: "duck", appearance: "duck 🦆" },
  { name: "turkey", appearance: "turkey 🦃" },
  { name: "goose", appearance: "goose 🦢" },
  { name: "swan", appearance: "swan 🦢" },
  { name: "rabbit", appearance: "rabbit 🐇" },
  { name: "turtle", appearance: "turtle 🐢" },
  { name: "frog", appearance: "frog 🐸" },
  { name: "snake", appearance: "snake 🐍" },
  { name: "lizard", appearance: "lizard 🦎" },
  { name: "crocodile", appearance: "crocodile 🐊" },
  { name: "dolphin", appearance: "dolphin 🐬" },
  { name: "whale", appearance: "whale 🐋" },
  { name: "shark", appearance: "shark 🦈" },
  { name: "octopus", appearance: "octopus 🐙" },
  { name: "crab", appearance: "crab 🦀" },
  { name: "lobster", appearance: "lobster 🦞" },
  { name: "shrimp", appearance: "shrimp 🦐" },
  { name: "squid", appearance: "squid 🦑" },
  { name: "snail", appearance: "snail 🐌" },
  { name: "butterfly", appearance: "butterfly 🦋" },
  { name: "ant", appearance: "ant 🐜" },
  { name: "bee", appearance: "bee 🐝" },
  { name: "lady beetle", appearance: "lady beetle 🐞" },
  { name: "scorpion", appearance: "scorpion 🦂" },
  { name: "mosquito", appearance: "mosquito 🦟" },
  { name: "fly", appearance: "fly 🪰" },
  { name: "dragonfly", appearance: "dragonfly 🪰" },
  { name: "cockroach", appearance: "cockroach 🪳" },
  { name: "spider", appearance: "spider 🕷️" },
  { name: "tarantula", appearance: "tarantula 🕷️" },
  { name: "grasshopper", appearance: "grasshopper 🦗" },
  { name: "cricket", appearance: "cricket 🦗" },
  { name: "beetle", appearance: "beetle 🪲" },
  { name: "caterpillar", appearance: "caterpillar 🐛" },
  { name: "centipede", appearance: "centipede 🐛" },
  { name: "mantis", appearance: "mantis 🦗" },
  { name: "dragon", appearance: "dragon 🐉" },
  { name: "unicorn", appearance: "unicorn 🦄" },
  { name: "penguin", appearance: "penguin 🐧" },
  { name: "koala", appearance: "koala 🐨" },
  { name: "panda", appearance: "panda 🐼" },
  { name: "sloth", appearance: "sloth 🦥" },
  { name: "orangutan", appearance: "orangutan 🦧" },
  { name: "gorilla", appearance: "gorilla 🦍" },
  { name: "elephant", appearance: "elephant 🐘" },
  { name: "rhinoceros", appearance: "rhinoceros 🦏" },
  { name: "hippopotamus", appearance: "hippopotamus 🦛" },
  { name: "buffalo", appearance: "buffalo 🦬" },
  { name: "ox", appearance: "ox 🐂" },
  { name: "kangaroo", appearance: "kangaroo 🦘" },
  { name: "lemur", appearance: "lemur 🐒" },
  { name: "monkey", appearance: "monkey 🐵" },
  { name: "tiger", appearance: "tiger 🐅" },
  { name: "lion", appearance: "lion 🦁" },
  { name: "cheetah", appearance: "cheetah 🐆" },
  { name: "leopard", appearance: "leopard 🐆" },
  { name: "panther", appearance: "panther 🐆" },
  { name: "jaguar", appearance: "jaguar 🐆" },
  { name: "bear", appearance: "bear 🐻" },
  { name: "polar bear", appearance: "polar bear 🐻" },
  { name: "grizzly bear", appearance: "grizzly bear 🐻" },
  { name: "brown bear", appearance: "brown bear 🐻" },
  { name: "puma", appearance: "puma 🐆" },
  { name: "lynx", appearance: "lynx 🐆" },
  { name: "bobcat", appearance: "bobcat 🐆" },
  { name: "wolf", appearance: "wolf 🐺" },
  { name: "fox", appearance: "fox 🦊" },
  { name: "coyote", appearance: "coyote 🐺" },
  { name: "hyena", appearance: "hyena 🐾" },
  { name: "jackal", appearance: "jackal 🐺" },
  { name: "hare", appearance: "hare 🐇" },
  { name: "wallaby", appearance: "wallaby 🦘" },
  { name: "opossum", appearance: "opossum 🐾" },
  { name: "wombat", appearance: "wombat 🐨" },
  { name: "platypus", appearance: "platypus 🦆" },
  { name: "baboon", appearance: "baboon 🐒" },
  { name: "chimp", appearance: "chimp 🐵" },
  { name: "gibbon", appearance: "gibbon 🦧" },
  { name: "macaque", appearance: "macaque 🐒" },
  { name: "squirrel monkey", appearance: "squirrel monkey 🐒" },
  { name: "capuchin", appearance: "capuchin 🐒" },
  { name: "tamarin", appearance: "tamarin 🐒" },
  { name: "howler monkey", appearance: "howler monkey 🐒" },
  { name: "spider monkey", appearance: "spider monkey 🐒" },
  { name: "marmoset", appearance: "marmoset 🐒" },
  { name: "bonobo", appearance: "bonobo 🐒" },
  { name: "anteater", appearance: "anteater 🐜" },
  { name: "armadillo", appearance: "armadillo 🦣" },
  { name: "aardvark", appearance: "aardvark 🐜" },
  { name: "porcupine", appearance: "porcupine 🦔" },
  { name: "hedgehog", appearance: "hedgehog 🦔" },
  { name: "badger", appearance: "badger 🦡" },
  { name: "otter", appearance: "otter 🦦" },
  { name: "weasel", appearance: "weasel 🐾" },
  { name: "ferret", appearance: "ferret 🐾" },
  { name: "stoat", appearance: "stoat 🐾" },
  { name: "mink", appearance: "mink 🐾" },
  { name: "mongoose", appearance: "mongoose 🐾" },
  { name: "rat", appearance: "rat 🐀" },
  { name: "mouse", appearance: "mouse 🐁" },
  { name: "hamster", appearance: "hamster 🐹" },
  { name: "sloth bear", appearance: "sloth bear 🐻" },
  { name: "sun bear", appearance: "sun bear 🐻" },
  { name: "spectacled bear", appearance: "spectacled bear 🐻" },
  { name: "pangolin", appearance: "pangolin 🐜" },
  { name: "anteater", appearance: "anteater 🐜" },
  { name: "numbat", appearance: "numbat 🐜" },
  { name: "quokka", appearance: "quokka 🦘" },
  { name: "kookaburra", appearance: "kookaburra 🦜" },
  { name: "cassowary", appearance: "cassowary 🦃" },
  { name: "emu", appearance: "emu 🦃" },
  { name: "kiwi", appearance: "kiwi 🥝" },
  { name: "okapi", appearance: "okapi 🦒" },
  { name: "quoll", appearance: "quoll 🐾" },
  { name: "numbat", appearance: "numbat 🐜" },
  { name: "vicuña", appearance: "vicuña 🦙" },
  { name: "yak", appearance: "yak 🐂" },
  { name: "bison", appearance: "bison 🦬" },
  { name: "gnu", appearance: "gnu 🦏" },
  { name: "ibex", appearance: "ibex 🐐" },
  { name: "marmot", appearance: "marmot 🐿️" },
  { name: "lemming", appearance: "lemming 🐭" },
  { name: "vole", appearance: "vole 🐀" },
  { name: "shrew", appearance: "shrew 🐁" },
  { name: "chipmunk", appearance: "chipmunk 🐿️" },
  { name: "squirrel", appearance: "squirrel 🐿️" },
  { name: "marsupial mole", appearance: "marsupial mole 🦘" },
];

export interface Occupation {
  name: string;
  description: string;
}

export const occupations: Occupation[] = [
  { name: "Accountant", description: "accountant 📊" },
  { name: "Actor/Actress", description: "actor/actress 🎭" },
  { name: "Architect", description: "architect 🏗️" },
  { name: "Artist", description: "artist 🎨" },
  { name: "Astronaut", description: "astronaut 🚀" },
  { name: "Athlete", description: "athlete 🏅" },
  { name: "Author", description: "author 📚" },
  { name: "Baker", description: "baker 🥖" },
  { name: "Barista", description: "barista ☕" },
  { name: "Bartender", description: "bartender 🍹" },
  { name: "Chef", description: "chef 👨‍🍳" },
  { name: "Carpenter", description: "carpenter 🔨" },
  { name: "CEO", description: "CEO 💼" },
  { name: "Dancer", description: "dancer 💃" },
  { name: "Dentist", description: "dentist 😷" },
  { name: "Doctor", description: "doctor 👩‍⚕️" },
  { name: "Engineer", description: "engineer 👷‍♂️" },
  { name: "Firefighter", description: "firefighter 👨‍🚒" },
  { name: "Flight Attendant", description: "flight attendant ✈️" },
  { name: "Graphic Designer", description: "graphic designer 🎨" },
  { name: "Hairdresser", description: "hairdresser 💇" },
  { name: "Journalist", description: "journalist 📰" },
  { name: "Lawyer", description: "lawyer ⚖️" },
  { name: "Librarian", description: "librarian 📚" },
  { name: "Mechanic", description: "mechanic 🔧" },
  { name: "Musician", description: "musician 🎵" },
  { name: "Nurse", description: "nurse 👩‍⚕️" },
  { name: "Painter", description: "painter 🎨" },
  { name: "Photographer", description: "photographer 📸" },
  { name: "Pilot", description: "pilot ✈️" },
  { name: "Plumber", description: "plumber 🔧" },
  { name: "Police Officer", description: "police officer 👮" },
  { name: "Professor", description: "professor 👨‍🏫" },
  { name: "Psychologist", description: "psychologist 👨‍⚕️" },
  { name: "Real Estate Agent", description: "real estate agent 🏠" },
  { name: "Scientist", description: "scientist 👩‍🔬" },
  { name: "Software Developer", description: "software developer 💻" },
  { name: "Student", description: "student 🎓" },
  { name: "Teacher", description: "teacher 👩‍🏫" },
  { name: "Veterinarian", description: "veterinarian 🐾" },
  { name: "Waiter/Waitress", description: "waiter/waitress 🍽️" },
  { name: "Writer", description: "writer ✍️" },
  { name: "Electrician", description: "electrician ⚡" },
  { name: "Plumber", description: "plumber 🔧" },
  { name: "Salesperson", description: "salesperson 💼" },
  { name: "Consultant", description: "consultant 💼" },
  { name: "Entrepreneur", description: "entrepreneur 💼" },
  { name: "Pharmacist", description: "pharmacist 💊" },
  { name: "Actor/Actress", description: "actor/actress 🎭" },
  { name: "Counselor", description: "counselor 🧘" },
  { name: "Financial Analyst", description: "financial analyst 💹" },
  { name: "Social Worker", description: "social worker 👨‍👦" },
  { name: "Secretary", description: "secretary 💼" },
  { name: "Receptionist", description: "receptionist 💼" },
  { name: "Delivery Driver", description: "delivery driver 🚚" }
]

export interface Hobby {
  name: string;
  description: string;
}

export const hobbies: Hobby[] = [
  // Existing hobbies
  { name: "reading", description: "reading 📚" },
  { name: "writing", description: "writing 📝" },
  { name: "drawing", description: "drawing 🎨" },
  { name: "painting", description: "painting 🖌️" },
  { name: "sculpting", description: "sculpting 🗿" },
  { name: "photography", description: "photography 📷" },
  { name: "cooking", description: "cooking 🍳" },
  { name: "baking", description: "baking 🍰" },
  { name: "gardening", description: "gardening 🌱" },
  { name: "fishing", description: "fishing 🎣" },
  { name: "hiking", description: "hiking 🥾" },
  { name: "camping", description: "camping ⛺" },
  { name: "traveling", description: "traveling ✈️" },
  { name: "swimming", description: "swimming 🏊" },
  { name: "running", description: "running 🏃" },
  { name: "cycling", description: "cycling 🚴" },
  { name: "yoga", description: "yoga 🧘" },
  { name: "meditation", description: "meditation 🧘" },
  { name: "dancing", description: "dancing 💃" },
  { name: "singing", description: "singing 🎤" },
  { name: "playing", description: "playing 🎸" },
  { name: "watching", description: "watching 🎬" },
  { name: "listening", description: "listening 🎧" },
  { name: "solving", description: "solving 🧩" },
  { name: "collecting", description: "collecting 📬" },
  { name: "knitting", description: "knitting 🧶" },
  { name: "crocheting", description: "crocheting 🧶" },
  { name: "sewing", description: "sewing 🧵" },
  { name: "quilting", description: "quilting 🪡" },
  { name: "woodworking", description: "woodworking 🔨" },
  { name: "metalworking", description: "metalworking 🔧" },
  { name: "calligraphy", description: "calligraphy 🖋️" },
  { name: "lettering", description: "lettering ✍️" },
  { name: "origami", description: "origami 🎏" },
  { name: "scrapbooking", description: "scrapbooking 📒" },
  { name: "journaling", description: "journaling 📓" },
  { name: "birdwatching", description: "birdwatching 🦜" },
  { name: "stargazing", description: "stargazing 🔭" },
  { name: "metaldetecting", description: "metaldetecting 🕵️‍♂️" },
  { name: "skydiving", description: "skydiving 🪂" },
  { name: "bungeejumping", description: "bungeejumping 🪂" },
  { name: "rockclimbing", description: "rockclimbing 🧗‍♂️" },
  { name: "surfing", description: "surfing 🏄" },
  { name: "snowboarding", description: "snowboarding 🏂" },
  { name: "skiing", description: "skiing ⛷️" },
  { name: "kayaking", description: "kayaking 🚣" },
  { name: "canoeing", description: "canoeing 🛶" },
  { name: "rafting", description: "rafting 🛶" },
  { name: "skateboarding", description: "skateboarding 🛹" },
  { name: "inline", description: "inline 🛹" },
  { name: "iceskating", description: "iceskating ⛸️" },
  { name: "rollerskating", description: "rollerskating 🛼" },
  { name: "horseback", description: "horseback 🐎" },
];

export interface Interests {
  name: string;
  description: string;
}

export const interests: Interests[] = [
  // Existing interests
  { name: "birdwatching", description: "birdwatching 🦜" },
  { name: "stargazing", description: "stargazing 🔭" },
  { name: "metaldetecting", description: "metaldetecting 🕵️‍♂️" },
  { name: "skydiving", description: "skydiving 🪂" },
  { name: "bungeejumping", description: "bungeejumping 🪂" },
  { name: "rockclimbing", description: "rockclimbing 🧗‍♂️" },
  { name: "surfing", description: "surfing 🏄" },
  { name: "snowboarding", description: "snowboarding 🏂" },
  { name: "skiing", description: "skiing ⛷️" },
  { name: "kayaking", description: "kayaking 🚣" },
  { name: "canoeing", description: "canoeing 🛶" },
  { name: "rafting", description: "rafting 🛶" },
  { name: "skateboarding", description: "skateboarding 🛹" },
  { name: "inline", description: "inline 🛹" },
  { name: "iceskating", description: "iceskating ⛸️" },
  { name: "rollerskating", description: "rollerskating 🛼" },
  { name: "horseback", description: "horseback 🐎" },
  { name: "mountaineering", description: "mountaineering ⛰️" },
  { name: "paragliding", description: "paragliding 🪂" },
  { name: "kitesurfing", description: "kitesurfing 🪁" },
  { name: "caving", description: "caving 🕳️" },
  { name: "backpacking", description: "backpacking 🎒" },
  { name: "bouldering", description: "bouldering 🧗‍♂️" },
  { name: "kiteboarding", description: "kiteboarding 🏄"}
];

export interface Language {
  name: string;
  description: string;
}


export const languages: Language[] = [
  { name: "English", description: "english 🇬🇧" },
  { name: "Spanish", description: "spanish 🇪🇸" },
  { name: "Mandarin", description: "mandarin 🇨🇳" },
  { name: "Hindi", description: "hindi 🇮🇳" },
  { name: "French", description: "french 🇫🇷" },
  { name: "Arabic", description: "arabic 🇸🇦" },
  { name: "Bengali", description: "bengali 🇧🇩" },
  { name: "Russian", description: "russian 🇷🇺" },
  { name: "Portuguese", description: "portuguese 🇵🇹" },
  { name: "Urdu", description: "urdu 🇵🇰" },
  { name: "German", description: "german 🇩🇪" },
  { name: "Japanese", description: "japanese 🇯🇵" },
  { name: "Swahili", description: "swahili 🇰🇪" },
  { name: "Korean", description: "korean 🇰🇷" },
  { name: "Italian", description: "italian 🇮🇹" },
  { name: "Turkish", description: "turkish 🇹🇷" },
  { name: "Vietnamese", description: "vietnamese 🇻🇳" },
  { name: "Tamil", description: "tamil 🇮🇳" },
  { name: "Telugu", description: "telugu 🇮🇳" },
  { name: "Marathi", description: "marathi 🇮🇳" },
  { name: "Wu", description: "wu 🇨🇳" },
  { name: "Xiang", description: "xiang 🇨🇳" },
  { name: "Malayalam", description: "malayalam 🇮🇳" },
  { name: "Persian", description: "persian 🇮🇷" },
  { name: "Javanese", description: "javanese 🇮🇩" },
  { name: "Lahnda", description: "lahnda 🇵🇰" },
  { name: "Burmese", description: "burmese 🇲🇲" },
  { name: "Yoruba", description: "yoruba 🇳🇬" },
  { name: "Sundanese", description: "sundanese 🇮🇩" },
  { name: "Ukrainian", description: "ukrainian 🇺🇦" },
  { name: "Sindhi", description: "sindhi 🇵🇰" },
  { name: "Romanian", description: "romanian 🇷🇴" },
  { name: "Igbo", description: "igbo 🇳🇬" },
  { name: "Tagalog", description: "tagalog 🇵🇭" },
  { name: "Dutch", description: "dutch 🇳🇱" },
  { name: "Amharic", description: "amharic 🇪🇹" },
  { name: "Oromo", description: "oromo 🇪🇹" },
  { name: "Serbo-Croatian", description: "serbo-croatian 🇷🇸" },
  { name: "Thai", description: "thai 🇹🇭" },
  { name: "Saraiki", description: "saraiki 🇵🇰" },
  { name: "Burmese", description: "burmese 🇲🇲" },
  { name: "Malay", description: "malay 🇲🇾" },
  { name: "Hausa", description: "hausa 🇳🇬" },
  { name: "Bhojpuri", description: "bhojpuri 🇮🇳" },
  { name: "Indonesian", description: "indonesian 🇮🇩" },
  { name: "Polish", description: "polish 🇵🇱" },
  { name: "Yue", description: "yue 🇨🇳" },
  { name: "Farsi", description: "farsi 🇮🇷" },
  { name: "Gujarati", description: "gujarati 🇮🇳" },
  { name: "Sinhala", description: "sinhala 🇱🇰" },
  { name: "Arabic", description: "arabic 🇸🇦" },
{ name: "Bengali", description: "bengali 🇧🇩" },
{ name: "Russian", description: "russian 🇷🇺" },
{ name: "Portuguese", description: "portuguese 🇵🇹" },
{ name: "Urdu", description: "urdu 🇵🇰" },
{ name: "German", description: "german 🇩🇪" },
{ name: "Japanese", description: "japanese 🇯🇵" },
{ name: "Swahili", description: "swahili 🇰🇪" },
{ name: "Korean", description: "korean 🇰🇷" },
{ name: "Italian", description: "italian 🇮🇹" },
{ name: "Turkish", description: "turkish 🇹🇷" },
{ name: "Vietnamese", description: "vietnamese 🇻🇳" },
{ name: "Tamil", description: "tamil 🇮🇳" },
{ name: "Telugu", description: "telugu 🇮🇳" },
{ name: "Marathi", description: "marathi 🇮🇳" },
{ name: "Wu", description: "wu 🇨🇳" },
{ name: "Xiang", description: "xiang 🇨🇳" },
{ name: "Malayalam", description: "malayalam 🇮🇳" },
{ name: "Persian", description: "persian 🇮🇷" },
{ name: "Javanese", description: "javanese 🇮🇩" },
{ name: "Lahnda", description: "lahnda 🇵🇰" },
{ name: "Burmese", description: "burmese 🇲🇲" },
{ name: "Yoruba", description: "yoruba 🇳🇬" },
{ name: "Sundanese", description: "sundanese 🇮🇩" },
{ name: "Ukrainian", description: "ukrainian 🇺🇦" },
{ name: "Sindhi", description: "sindhi 🇵🇰" },
{ name: "Romanian", description: "romanian 🇷🇴" },
{ name: "Igbo", description: "igbo 🇳🇬" },
{ name: "Tagalog", description: "tagalog 🇵🇭" },
{ name: "Dutch", description: "dutch 🇳🇱" },
{ name: "Amharic", description: "amharic 🇪🇹" },
{ name: "Oromo", description: "oromo 🇪🇹" },
{ name: "Serbo-Croatian", description: "serbo-croatian 🇷🇸" },
{ name: "Thai", description: "thai 🇹🇭" },
{ name: "Saraiki", description: "saraiki 🇵🇰" },
{ name: "Burmese", description: "burmese 🇲🇲" },
{ name: "Malay", description: "malay 🇲🇾" },
{ name: "Hausa", description: "hausa 🇳🇬" },
{ name: "Bhojpuri", description: "bhojpuri 🇮🇳" },
{ name: "Indonesian", description: "indonesian 🇮🇩" },
{ name: "Polish", description: "polish 🇵🇱" },
{ name: "Yue", description: "yue 🇨🇳" },
{ name: "Farsi", description: "farsi 🇮🇷" },
{ name: "Gujarati", description: "gujarati 🇮🇳" },
{ name: "Sinhala", description: "sinhala 🇱🇰" },
{ name: "Arabic", description: "arabic 🇸🇦" },
{ name: "Bengali", description: "bengali 🇧🇩" },
{ name: "Russian", description: "russian 🇷🇺" },
{ name: "Portuguese", description: "portuguese 🇵"}
];

export interface Gender {
  name: string;
  description: string;
}

export const genders: Gender[] = [
  { name: "male", description: "male ♂️" },
  { name: "female", description: "female ♀️" },
  { name: "non-binary", description: "non-binary ⚧️" },
  { name: "transgender", description: "transgender ⚧️" },
  { name: "genderqueer", description: "genderqueer 🏳️‍🌈" },
  { name: "agender", description: "agender 🏳️‍🌈" },
  { name: "bigender", description: "bigender 🏳️‍🌈" },
  { name: "genderfluid", description: "genderfluid 🏳️‍🌈" },
  { name: "two-spirit", description: "two-spirit 🏳️‍🌈" },
  { name: "pangender", description: "pangender 🏳️‍🌈" },
  { name: "androgyne", description: "androgyne 🏳️‍🌈" },
  { name: "neutrois", description: "neutrois 🏳️‍🌈" },
  { name: "demiboy", description: "demiboy 🏳️‍🌈" },
  { name: "demigirl", description: "demigirl 🏳️‍🌈" },
  { name: "gender questioning", description: "gender questioning 🏳️‍🌈" },
  { name: "gender variant", description: "gender variant 🏳️‍🌈" },
  { name: "intersex", description: "intersex 🏳️‍⚧️" },
];

export interface MusicGenre {
  name: string;
  description: string;
}

export const musicGenres: MusicGenre[] = [
  { name: "rock", description: "rock 🎸" },
  { name: "pop", description: "pop 🎤" },
  { name: "hip hop", description: "hip hop 🎵" },
  { name: "rap", description: "rap 🎤" },
  { name: "jazz", description: "jazz 🎷" },
  { name: "blues", description: "blues 🎵" },
  { name: "country", description: "country 🤠" },
  { name: "reggae", description: "reggae 🎵" },
  { name: "classical", description: "classical 🎻" },
  { name: "electronic", description: "electronic 🎧" },
  { name: "dance", description: "dance 💃" },
  { name: "folk", description: "folk 🎵" },
  { name: "indie", description: "indie 🎸" },
  { name: "alternative", description: "alternative 🎵" },
  { name: "metal", description: "metal 🤘" },
  { name: "punk", description: "punk 🤘" },
  { name: "reggaeton", description: "reggaeton 🎵" },
  { name: "soul", description: "soul 🎤" },
  { name: "funk", description: "funk 🎵" },
  { name: "r&b", description: "r&b 🎵" },
  { name: "gospel", description: "gospel 🎤" },
  { name: "ambient", description: "ambient 🎶" },
  { name: "techno", description: "techno 🔊" },
  { name: "trance", description: "trance 🔊" },
  { name: "house", description: "house 🏠" },
  { name: "reggaeton", description: "reggaeton 🎵" },
  { name: "salsa", description: "salsa 💃" },
  { name: "bachata", description: "bachata 💃" },
  { name: "merengue", description: "merengue 💃" },
  { name: "cumbia", description: "cumbia 💃" },
  { name: "ska", description: "ska 🎷" },
  { name: "bluegrass", description: "bluegrass 🎻" },
  { name: "edm", description: "edm 🎧" },
  { name: "house", description: "house 🏠" },
  { name: "dubstep", description: "dubstep 🎧" },
  { name: "trap", description: "trap 🎧" },
  { name: "ambient", description: "ambient 🎶" },
  { name: "folk", description: "folk 🎵" },
  { name: "latin", description: "latin 🎵" },
  { name: "disco", description: "disco 💃" },
];

export interface Color {
  name: string;
  hex: string;
}
export const colors: Color[] = [
  { name: "red", hex: "#FF0000" },
  { name: "orange", hex: "#FFA500" },
  { name: "yellow", hex: "#FFFF00" },
  { name: "green", hex: "#008000" },
  { name: "blue", hex: "#0000FF" },
  { name: "purple", hex: "#800080" },
  { name: "pink", hex: "#FFC0CB" },
  { name: "brown", hex: "#A52A2A" },
  { name: "black", hex: "#000000" },
  { name: "white", hex: "#FFFFFF" },
  { name: "gray", hex: "#808080" },
  { name: "silver", hex: "#C0C0C0" },
  { name: "gold", hex: "#FFD700" },
  { name: "cyan", hex: "#00FFFF" },
  { name: "magenta", hex: "#FF00FF" },
  { name: "maroon", hex: "#800000" },
  { name: "olive", hex: "#808000" },
  { name: "lime", hex: "#00FF00" },
  { name: "teal", hex: "#008080" },
  { name: "navy", hex: "#000080" },
  { name: "indigo", hex: "#4B0082" },
  { name: "turquoise", hex: "#40E0D0" },
  { name: "lavender", hex: "#E6E6FA" },
  { name: "violet", hex: "#8A2BE2" },
  { name: "orchid", hex: "#DA70D6" },
  { name: "salmon", hex: "#FA8072" },
  { name: "coral", hex: "#FF7F50" },
  { name: "sky blue", hex: "#87CEEB" },
  { name: "azure", hex: "#F0FFFF" },
  { name: "aquamarine", hex: "#7FFFD4" },
  { name: "tan", hex: "#D2B48C" },
  { name: "khaki", hex: "#F0E68C" },
  { name: "beige", hex: "#F5F5DC" },
  { name: "peach", hex: "#FFE5B4" },
  { name: "plum", hex: "#DDA0DD" },
  { name: "chartreuse", hex: "#7FFF00" },
  { name: "sienna", hex: "#A0522D" },
  { name: "chocolate", hex: "#D2691E" },
  { name: "tan", hex: "#D2B48C" },
  { name: "peru", hex: "#CD853F" },
  { name: "bisque", hex: "#FFE4C4" },
  { name: "wheat", hex: "#F5DEB3" },
  { name: "tan", hex: "#D2B48C" },
  { name: "mint", hex: "#98FF98" },
  { name: "alice blue", hex: "#F0F8FF" },
  { name: "lavender blush", hex: "#FFF0F5" },
  { name: "powder blue", hex: "#B0E0E6" },
  { name: "light pink", hex: "#FFB6C1" },
  { name: "pale green", hex: "#98FB98" },
  { name: "cornsilk", hex: "#FFF8DC" },
  { name: "papaya whip", hex: "#FFEFD5" },
  { name: "light blue", hex: "#ADD8E6" },
  { name: "medium purple", hex: "#9370DB" },
  { name: "light salmon", hex: "#FFA07A" },
  { name: "peach puff", hex: "#FFDAB9" },
  { name: "light green", hex: "#90EE90" },
  { name: "medium orchid", hex: "#BA55D3" },
  { name: "light coral", hex: "#F08080" },
  { name: "light sky blue", hex: "#87CEFA" },
  { name: "thistle", hex: "#D8BFD8" },
  { name: "light gray", hex: "#D3D3D3" },
  { name: "pale violet red", hex: "#DB7093" },
  { name: "light steel blue", hex: "#B0C4DE" },
  { name: "cornflower blue", hex: "#6495ED" },
  { name: "light goldenrod yellow", hex: "#FAFAD2" },
  { name: "light slate gray", hex: "#778899" },
  { name: "lavender", hex: "#E6E6FA" },
  { name: "light sea green", hex: "#20B2AA" },
  { name: "light pink", hex: "#FFB6C1" },
  { name: "light cyan", hex: "#E0FFFF" },
  { name: "light salmon", hex: "#FFA07A" },
  { name: "light yellow", hex: "#FFFFE0" },
  { name: "light sky blue", hex: "#87CEFA" },
  { name: "light coral", hex: "#F08080" },
  { name: "light green", hex: "#90EE90" },
  { name: "light blue", hex: "#ADD8E6" },
  { name: "light steel blue", hex: "#B0C4DE" },
  { name: "light gray", hex: "#D3D3D3" },
  { name: "light goldenrod yellow", hex: "#FAFAD2" },
  { name: "light cyan", hex: "#E0FFFF" },
  { name: "light pink", hex: "#FFB6C1" },
  { name: "light steel blue", hex: "#B0C4DE" },
  { name: "light salmon", hex: "#FFA07A" },
  { name: "light sky blue", hex: "#87CEFA" },
  { name: "light green", hex: "#90EE90" },
  { name: "light coral", hex: "#F08080" },
  { name: "light blue", hex: "#ADD8E6" },
  { name: "light goldenrod yellow", hex: "#FAFAD2" },
  { name: "light gray", hex: "#D3D3D3" },
  { name: "light yellow", hex: "#FFFFE0" },
  { name: "medium aquamarine", hex: "#66CDAA" },
  { name: "medium blue", hex: "#0000CD" },
  { name: "medium orchid", hex: "#BA55D3" },
  { name: "medium purple", hex: "#9370DB" },
  { name: "medium sea green", hex: "#3CB371" },
  { name: "medium slate blue", hex: "#7B68EE" },
  { name: "medium spring green", hex: "#00FA9A" },
  { name: "medium turquoise", hex: "#48D1CC" },
  { name: "medium violet-red", hex: "#C71585" },
  { name: "midnight blue", hex: "#191970" },
  { name: "misty rose", hex: "#FFE4E1" },
  { name: "moccasin", hex: "#FFE4B5" },
  { name: "navajo white", hex: "#FFDEAD" },
  { name: "old lace", hex: "#FDF5E6" },
  { name: "olive drab", hex: "#6B8E23" },
  { name: "orange red", hex: "#FF4500" },
  { name: "orchid", hex: "#DA70D6" },
  { name: "pale goldenrod", hex: "#EEE8AA" },
  { name: "pale green", hex: "#98FB98" },
  { name: "pale turquoise", hex: "#AFEEEE" },
  { name: "pale violet-red", hex: "#DB7093" },
  { name: "papaya whip", hex: "#FFEFD5" },
  { name: "peach puff", hex: "#FFDAB9" },
  { name: "peru", hex: "#CD853F" },
  { name: "powder blue", hex: "#B0E0E6" },
  { name: "rosy brown", hex: "#BC8F8F" },
  { name: "royal blue", hex: "#4169E1" },
  { name: "saddle brown", hex: "#8B4513" },
  { name: "sandy brown", hex: "#F4A460" },
  { name: "sea green", hex: "#2E8B57" },
  { name: "seashell", hex: "#FFF5EE" },
  { name: "sienna", hex: "#A0522D" },
  { name: "sky blue", hex: "#87CEEB" },
  { name: "slate blue", hex: "#6A5ACD" },
  { name: "slate gray", hex: "#708090" },
  { name: "snow", hex: "#FFFAFA" },
  { name: "spring green", hex: "#00FF7F" },
  { name: "steel blue", hex: "#4682B4" },
  { name: "tan", hex: "#D2B48C" },
  { name: "thistle", hex: "#D8BFD8" },
  { name: "tomato", hex: "#FF6347" },
  { name: "turquoise", hex: "#40E0D0" },
  { name: "violet", hex: "#8A2BE2" },
  { name: "wheat", hex: "#F5DEB3" },
  { name: "white smoke", hex: "#F5F5F5" },
  { name: "yellow green", hex: "#9ACD32" },
];

export interface ZodiacSign {
  name: string;
  description: string;
}
export const zodiacSigns: ZodiacSign[] = [
  { name: "aries", description: "aries ♈️" },
  { name: "taurus", description: "taurus ♉️" },
  { name: "gemini", description: "gemini ♊️" },
  { name: "cancer", description: "cancer ♋️" },
  { name: "leo", description: "leo ♌️" },
  { name: "virgo", description: "virgo ♍️" },
  { name: "libra", description: "libra ♎️" },
  { name: "scorpio", description: "scorpio ♏️" },
  { name: "sagittarius", description: "sagittarius ♐️" },
  { name: "capricorn", description: "capricorn ♑️" },
  { name: "aquarius", description: "aquarius ♒️" },
  { name: "pisces", description: "pisces ♓️" },
];

export interface Food {
  name: string;
  description: string;
}

export const foods: Food[] = [
  { name: "pizza", description: "pizza 🍕" },
  { name: "burger", description: "burger 🍔" },
  { name: "taco", description: "taco 🌮" },
  { name: "sushi", description: "sushi 🍣" },
  { name: "pasta", description: "pasta 🍝" },
  { name: "salad", description: "salad 🥗" },
  { name: "steak", description: "steak 🥩" },
  { name: "fried chicken", description: "fried chicken 🍗" },
  { name: "sandwich", description: "sandwich 🥪" },
  { name: "ramen", description: "ramen 🍜" },
  { name: "pancake", description: "pancake 🥞" },
  { name: "ice cream", description: "ice cream 🍨" },
  { name: "cake", description: "cake 🍰" },
  { name: "cookie", description: "cookie 🍪" },
  { name: "doughnut", description: "doughnut 🍩" },
  { name: "chocolate", description: "chocolate 🍫" },
  { name: "popcorn", description: "popcorn 🍿" },
  { name: "french fries", description: "french fries 🍟" },
  { name: "burrito", description: "burrito 🌯" },
  { name: "noodles", description: "noodles 🍜" },
  { name: "cheese", description: "cheese 🧀" },
  { name: "fruit", description: "fruit 🍉" },
  { name: "vegetables", description: "vegetables 🥦" },
  { name: "soup", description: "soup 🍲" },
  { name: "hot dog", description: "hot dog 🌭" },
  { name: "poke bowl", description: "poke bowl 🍲" },
  { name: "pad thai", description: "pad thai 🍜" },
  { name: "sashimi", description: "sashimi 🍣" },
  { name: "tempura", description: "tempura 🍤" },
  { name: "gyro", description: "gyro 🥙" },
  { name: "samosa", description: "samosa 🥟" },
  { name: "spring roll", description: "spring roll 🍱" },
  { name: "calzone", description: "calzone 🍕" },
  { name: "fajitas", description: "fajitas 🌯" },
  { name: "chowder", description: "chowder 🥣" },
  { name: "meatball", description: "meatball 🍖" },
  { name: "quiche", description: "quiche 🥚" },
  { name: "scone", description: "scone 🍰" },
  { name: "croissant", description: "croissant 🥐" },
  { name: "bagel", description: "bagel 🥯" },
  { name: "caviar", description: "caviar 🐟" },
  { name: "lobster", description: "lobster 🦞" },
  { name: "crab", description: "crab 🦀" },
  { name: "shrimp", description: "shrimp 🦐" },
  { name: "scallop", description: "scallop 🐚" },
  { name: "oyster", description: "oyster 🦪" },
  { name: "clam", description: "clam 🐚" },
  { name: "mussel", description: "mussel 🐚" },
  { name: "squid", description: "squid 🦑" },
  { name: "octopus", description: "octopus 🐙" },
  { name: "eel", description: "eel 🐍" },
  { name: "snail", description: "snail 🐌" },
  { name: "frog legs", description: "frog legs 🐸" },
  { name: "escargot", description: "escargot 🐌" },
  { name: "hummus", description: "hummus 🧆" },
  { name: "falafel", description: "falafel 🧆" },
  { name: "poutine", description: "poutine 🍟" },
  { name: "pierogi", description: "pierogi 🥟" },
  { name: "risotto", description: "risotto 🍚" },
  { name: "fondue", description: "fondue 🧀" },
  { name: "biryani", description: "biryani 🍛" },
  { name: "bibimbap", description: "bibimbap 🍲" },
  { name: "satay", description: "satay 🍢" },
  { name: "schnitzel", description: "schnitzel 🍖" },
  { name: "pulled pork", description: "pulled pork 🍖" },
  { name: "veal", description: "veal 🐄" },
  { name: "lamb", description: "lamb 🐑" },
  { name: "duck", description: "duck 🦆" },
  { name: "goose", description: "goose 🦢" },
  { name: "quail", description: "quail 🦜" },
  { name: "rabbit", description: "rabbit 🐇" },
  { name: "venison", description: "venison 🦌" },
  { name: "wild boar", description: "wild boar 🐗" },
  { name: "elk", description: "elk 🦌" },
  { name: "bison", description: "bison 🦬" },
  { name: "moose", description: "moose 🦌" }
];